### ISSUE TITLE
Server starts,  messages cause an exception- 

### ISSUE THREAD

**Issue by ProsperCraft** [shadowfacts/DiscordChat#107]
The server starts, which is announced to the proper discord channel, then a message typed in discord results in this error in console.

```
[17:34:18] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [17:34:18] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[17:34:18] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [17:34:18] [Fatal] [JDA]: Encountered an exception:
[17:34:18] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [17:34:18] [Fatal] [JDA]: java.lang.NullPointerException
        at net.shadowfacts.discordchat.core.Listener.onGuildMessageReceived(Listener.java:52)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:353)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:96)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:768)
        at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:498)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

DiscordChat version: DiscordChat-1.10.2-2.2.1

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
c3aa74c9a8ecaadfa7c26f63b3f508ef2ebcb04c
