### ISSUE TITLE
Bot connected to server but dont sending/receiving message 

### ISSUE THREAD

**Issue by LynSisCZ** [shadowfacts/DiscordChat#117]
Brief explanation of issue:
Bot connected to server but dont sending/receiving  message to/from discord/minecraft

Steps to reproduce:
- Step 1 
Follow the instruction on Setup Page 
- Step 2
Setting discord config and start 

Link to crash report/log in a [gist](https://gist.github.com): 
https://gist.github.com/DvnBthlo/036c9a7bf9e2cba3a330ddbcfbfaf663

DiscordChat version:  DiscordChat-1.7.10-2.3.0

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
Why was this closed? If you've solved the issue, post the solution.

**Comment by janagyjr** [comment]
I'd like to know as well since I still haven't gotten the integration to work.

**Comment by retep998** [comment]
I'm having the same issue!
<details><summary>server log</summary>

```
[23:56:34] [DiscordChat-initializer/INFO] [STDOUT/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [23:56:34] [Info] [JDA]: Login Successful!
[23:56:34] [JDA MainWS-WriteThread/INFO] [STDOUT/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:396]: [23:56:34] [Info] [JDASocket]: Connected to WebSocket
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"name":"Text","bitrate":64000,"position":0,"id":"361246138394869762","user_limit":0,"type":4}
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"name":"Voice","bitrate":64000,"position":1,"id":"361246179201253378","user_limit":0,"type":4}
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"name":"Text","bitrate":64000,"position":0,"id":"361246138394869762","user_limit":0,"type":4}
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361246138394869762
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"name":"Voice","bitrate":64000,"position":1,"id":"361246179201253378","user_limit":0,"type":4}
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361246179201253378
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Completed the setup for Guild: G:Official FTB Wiki(319443908725702656) without matching id in ReadyHandler cache
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: Encountered an exception:
[23:56:35] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [23:56:35] [Fatal] [JDASocket]: java.lang.NullPointerException
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$0(GuildCreateHandler.java:44)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:298)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:876)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:573)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:910)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

</details>
