### ISSUE TITLE
server crash while sending message, non-recurring

### ISSUE THREAD

**Issue by kreezxil** [shadowfacts/DiscordChat#121]
1.11.2-2.3.0 crashes dedicated server Forge 1.11.2 build 2516

Notes:
     seems like a one-off crash. It tried to send a message, then crashed the server.

crash report:
https://gist.github.com/7b3d39f024f35925831339c185bf985e

fml server latest:
https://gist.github.com/04717f58371e9bfaa1fcf3849e494d09

**Comment by ikkerens** [comment]
Managed to get a copy of this crash during the Discord downtime, Discord API was very unstable at the time. My guess is that the jda variable was null at this point.

```
java.lang.NullPointerException: Exception in server tick loop
        at net.shadowfacts.discordchat.core.DiscordChat.sendMessage(DiscordChat.java:216)
        at net.shadowfacts.discordchat.core.DiscordChat.sendMessage(DiscordChat.java:247)
        at net.shadowfacts.discordchat.one_twelve_two.ForgeEventHandler.onPlayerLoggedOut(ForgeEventHandler.java:41)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_468_ForgeEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:578)
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:456)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:212)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```
