### ISSUE TITLE
Crash on player logout

### ISSUE THREAD

**Issue by dannydjdk** [shadowfacts/DiscordChat#129]
Brief explanation of issue:
Minecraft server crashes periodically when a server disconnects from the server, apparently while attempting to print the "playerX left the game" message to Discord.

Steps to reproduce:
Have not been able to determine exact circumstances to reproduce. Crash is intermittent and does not happen at every disconnection, but happens several times a day.

Link to crash report:
https://pastebin.com/FjfZUfbX

DiscordChat version:
2.3.0
Minecraft version:
1.12.2
Forge version:
14.23.1.2555

**Comment by Pirog17000** [comment]
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.shadowfacts.discordchat.core.DiscordChat.sendMessage(DiscordChat.java:216)
    at net.shadowfacts.discordchat.core.DiscordChat.sendMessage(DiscordChat.java:247)
    at net.shadowfacts.discordchat.one_twelve_two.ForgeEventHandler.onPlayerLoggedOut(ForgeEventHandler.java:41)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_204_ForgeEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:579)
    at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387)
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:748)
```

Same here. Got crash on logout.
