### ISSUE TITLE
[1.12.2] server hang with npe on shutdown

### ISSUE THREAD

**Issue by kreezxil** [shadowfacts/DiscordChat#135]
Brief explanation of issue:
When I shut my server down for reboot, I get an npe from DiscordChat that locks it up hard!

Steps to reproduce:

1. install forge build 2691 or better
2. install discordchat chat latest for 1.12.2
3. set it up correctly
4. enter server console and issue **stop** command

```
[21:01:50] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Discord Chat (discordchat)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]: Caused by: java.lang.NullPointerException
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at net.shadowfacts.discordchat.core.DiscordChat.stop(DiscordChat.java:169)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at net.shadowfacts.discordchat.one_twelve_two.OneTwelveTwoMod.serverStopped(OneTwelveTwoMod.java:54)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at java.lang.reflect.Method.invoke(Method.java:498)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at java.lang.reflect.Method.invoke(Method.java:498)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:91]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[21:01:50] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.comm
```

DiscordChat version:
1.12.2-2.3.0

Minecraft version:
1.12.2-14.23.3.2691

**Comment by kreezxil** [comment]
using build 2705 now, here's another one, it's the same thing. https://pastebin.com/y5HVUBDT

**Comment by kreezxil** [comment]
Same issue on build 2707

https://pastebin.com/wfRHYp7J

**Comment by bchilcott** [comment]
Assuming this project is no longer being maintained, but in case anyone picks it back up, same happened to me here:

https://pastebin.com/2ypsmVjM
Minecraft: 1.12.2
Forge: 14.23.5.2847
MC Eternal, with this mod added.

**Comment by kreezxil** [comment]
I recommend switching to the following:

for 1.14.4 & 1.15.2
https://www.curseforge.com/minecraft/mc-mods/dcintegration

for 1.12.2 https://www.curseforge.com/minecraft/mc-mods/discordintegration

**Comment by bchilcott** [comment]
Can't believe I never found that myself, thanks!

**Comment by kreezxil** [comment]
No problem I found both some time ago when this one began to fail due to
advanced forge versions.
