### ISSUE TITLE
[1.7.10-2.3.0] Discord bot account goes online, doesn't relay messages or respond to commands.

### ISSUE THREAD

**Issue by cjay567** [shadowfacts/DiscordChat#138]
Brief explanation of issue:
When I start the server the bot goes online but messages from MC don't get relayed to Discord and vice versa.

Steps to reproduce:
- Step 1
Install mod to mods folder
- Step 2
Setup configs according to [this](https://rtfm.shadowfacts.net/discord-chat/setup/)
- Step 3
Start server

Link to crash report/log in a [gist](https://gist.github.com/tjpc3/5a8fb6dc112c5b29b11598cb7ad5c297):

DiscordChat version:
1.7.10-2.3.0

Minecraft version:
1.7.10

**Comment by H3roDude** [comment]
Got the same issue!

**Comment by BaccarWozat** [comment]
Same issue here. I have 2 servers with DiscordChat bots, one for 1.12.2 and one for 1.7.10. Both should post in different channels. The 1.7.10 one shows up but says nothing, doesn't accept commands, and doesn't relay messages either way.

**Comment by Tander** [comment]
1.7.10-2.3.0 - the issue still present. And it's not because of STDERROR's about groups.

```[00:29:08] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [00:29:08] [Fatal] [JDASocket]: Completed the setup for Guild: G:testing(614917233478598721) without matching id in ReadyHandler cache
[00:29:08] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [00:29:08] [Fatal] [JDASocket]: Encountered an exception:
[00:29:08] [JDA MainWS-ReadThread/INFO] [STDERR/discordchat]: [net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.utils.SimpleLog:print:394]: [00:29:08] [Fatal] [JDASocket]: java.lang.NullPointerException
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$0(GuildCreateHandler.java:44)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:298)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:876)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:573)
	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:910)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at net.shadowfacts.discordchat.repack.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)```
