### ISSUE TITLE
[1.8.9] Crash when joining game

### ISSUE THREAD

**Issue by Eufranio** [shadowfacts/DiscordChat#36]
```
`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/shadowfacts/discordchat/repack/net/dv8tion/jda/JDA
    at net.shadowfacts.discordchat.discord.DiscordThread.getChannel(DiscordThread.java:80)
    at net.shadowfacts.discordchat.discord.DiscordThread.sendMessageToAllChannels(DiscordThread.java:72)
    at net.shadowfacts.discordchat.ForgeEventHandler.onPlayerLoggedIn(ForgeEventHandler.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_ForgeEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:557)
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:175)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.shadowfacts.discordchat.repack.net.dv8tion.jda.JDA
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

`

**Comment by shadowfacts** [comment]
Can you post the whole crash log?

**Comment by Eufranio** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  IC2core (industrialcraft-2-2.3.243-ex18.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 18/05/16 17:17
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/shadowfacts/discordchat/repack/net/dv8tion/jda/JDA
    at net.shadowfacts.discordchat.discord.DiscordThread.getChannel(DiscordThread.java:80)
    at net.shadowfacts.discordchat.discord.DiscordThread.sendMessageToAllChannels(DiscordThread.java:72)
    at net.shadowfacts.discordchat.ForgeEventHandler.onPlayerLoggedIn(ForgeEventHandler.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_ForgeEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:557)
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:175)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.shadowfacts.discordchat.repack.net.dv8tion.jda.JDA
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 3.13.0-85-generic
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1726098568 bytes (1646 MB) / 3268935680 bytes (3117 MB) up to 7490502656 bytes (7143 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1855-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge] (forge-1.8.9-11.15.1.1855-universal.jar) 
    UCHIJAAAA   agricraft{2.0.0a3} [AgriCraft] (agricraft-2.0.0a3.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   Automagy{2.0.2} [Automagy] (Automagy-1.8.9-2.0.2.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
    UCHIJAAAA   mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.8-26} [Immersive Engineering] (ImmersiveEngineering-0.8-26.jar) 
    UCHIJAAAA   intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
    UCHIJAAAA   JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.6} [BuildCraft] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.6} [BC Silicon] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.6} [BC Transport] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.6} [BC Builders] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.6} [BC Energy] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.6} [BC Robotics] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.6} [BC Factory] (buildcraft-7.2.6.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.2.1} [BuildCraft Compat] (buildcraft-compat-7.2.1.jar) 
    UCHIJAAAA   Chameleon{1.8.9-1.1.2} [Chameleon] (Chameleon-1.8.9-1.1.2.jar) 
    UCHIJAAAA   mcmultipart{1.0.9} [MCMultiPart] (MCMultiPart-1.0.9-universal.jar) 
    UCHIJAAAA   chiselsandbits{8.9} [Chisels & Bits] (chiselsandbits-8.9.jar) 
    UCHIJAAAA   ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
    UCHIJAAAA   cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
    UCHIJAAAA   craftingtweaks{3.0.55} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.55.jar) 
    UCHIJAAAA   DiscordChat{1.0.6} [DiscordChat] (DiscordChat-1.8.9-1.0.7.jar) 
    UCHIJAAAA   endercore{1.8.9-0.3.0.14-beta} [EnderCore] (EnderCore-1.8.9-0.3.0.14-beta.jar) 
    UCHIJAAAA   EnderIO{1.8.9-3.0.0.26_alpha} [Ender IO] (EnderIO-1.8.9-3.0.0.26_alpha.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   graves{1.8.9-b47-universal} [Graves Mod] (graves-1.8.9-b47-universal.jar) 
    UCHIJAAAA   IC2{2.3.243-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.243-ex18.jar) 
    UCHIJAAAA   inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
    UCHIJAAAA   ifinder{1.0} [ItemFinder] (ItemFinder-1.8.9-1.0.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   harvestcraft{1.8.9d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.8.9d.jar) 
    UCHIJAAAA   progressiveautomation{1.6.44} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.44.jar) 
    UCHIJAAAA   Psi{beta-23} [Psi] (Psi-beta-23.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   shadowmc{3.0.0-SNAPSHOT} [ShadowMC] (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.6.4} [Storage Drawers] (StorageDrawers-1.8.9-2.6.4.jar) 
    UCHIJAAAA   worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
    UCHIJAAAA   denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.3.243-ex18.jar)

NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
  net.shadowfacts.shadowmc.core.ShadowMCTransformer
EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)

    EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 10; [EntityPlayerMP['PotterCraft_'/8067, l='world', x=87.72, y=69.16, z=220.54]]
    Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by shadowfacts** [comment]
Can you try running the same versions of DiscordChat and ShadowMC (with the same configs) in a separate instance without any other mods?

**Comment by Eufranio** [comment]
Yes, trying right now.

**Comment by Eufranio** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 16/05/16 13:27
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/shadowfacts/discordchat/repack/net/dv8tion/jda/JDA
    at net.shadowfacts.discordchat.discord.DiscordThread.getChannel(DiscordThread.java:80)
    at net.shadowfacts.discordchat.discord.DiscordThread.sendMessageToAllChannels(DiscordThread.java:72)
    at net.shadowfacts.discordchat.ForgeEventHandler.onPlayerLoggedOut(ForgeEventHandler.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_ForgeEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:562)
    at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:337)
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:706)
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:183)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.shadowfacts.discordchat.repack.net.dv8tion.jda.JDA
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 16 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 442739496 bytes (422 MB) / 606601216 bytes (578 MB) up to 1404043264 bytes (1339 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1855 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1855-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1855} [Minecraft Forge] (forge-1.8.9-11.15.1.1855-universal.jar) 
    UCHIJAAAA   DiscordChat{1.0.6} [DiscordChat] (DiscordChat-1.8.9-1.0.7.jar) 
    UCHIJAAAA   shadowmc{3.0.0-SNAPSHOT} [ShadowMC] (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar) 
    Loaded coremods (and transformers): 
ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT.jar)
  net.shadowfacts.shadowmc.core.ShadowMCTransformer
    Profiler Position: N/A (disabled)
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by shadowfacts** [comment]
ee29f7f704a24e87f05e7f50f579183d6aa72e21

Update to DiscordChat 1.0.8.

**Comment by Eufranio** [comment]
Will it be posted in /releases ?

**Comment by shadowfacts** [comment]
Yes

**Comment by Eufranio** [comment]
Same crash D:
@shadowfacts 

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/dv8tion/jda/JDA
    at net.shadowfacts.discordchat.discord.DiscordThread.getChannel(DiscordThread.java:80)
    at net.shadowfacts.discordchat.discord.DiscordThread.sendMessageToAllChannels(DiscordThread.java:72)
    at net.shadowfacts.discordchat.ForgeEventHandler.onPlayerLoggedIn(ForgeEventHandler.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_ForgeEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:557)
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:175)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.JDA
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by shadowfacts** [comment]
Can you try again in a different instance without any other mods? The `ArrayIndexOutOfBoundsException` is confusing me and shouldn't be happening :V

**Comment by Eufranio** [comment]
Of course, trying right now. :)

**Comment by Eufranio** [comment]
@shadowfacts 

```
[[18:58:23] [Server thread/TRACE] [DiscordChat/DiscordChat]: Sending event FMLServerStartingEvent to mod DiscordChat
[18:58:23] [Server thread/INFO] [DiscordChat/DiscordChat]: Connecting to the Discord server...
[18:58:23] [Server thread/ERROR] [DiscordChat/DiscordChat]: Problem starting DiscordChat, disabling
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]: java.lang.NoClassDefFoundError: net/dv8tion/jda/JDABuilder
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.shadowfacts.discordchat.discord.DiscordThread.run(DiscordThread.java:41)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at java.lang.Thread.run(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.shadowfacts.discordchat.discord.DiscordThread.runThread(DiscordThread.java:27)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.shadowfacts.discordchat.DiscordChat.serverStarting(DiscordChat.java:43)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at java.lang.reflect.Method.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at java.lang.reflect.Method.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at java.lang.reflect.Method.invoke(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:787)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:284)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:281)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [net.shadowfacts.shadowmc.util.LogHelper:error:46]:   at java.lang.Thread.run(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.JDABuilder
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]:     ... 34 more
[18:58:23] [Server thread/INFO] [STDERR/DiscordChat]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[18:58:23] [Server thread/TRACE] [DiscordChat/DiscordChat]: Sent event FMLServerStartingEvent to mod DiscordChat
[18:58:23] [Server thread/DEBUG] [FML/]: Bar Step: ServerStarting - DiscordChat took 0,517s]
```

**Comment by shadowfacts** [comment]
Try version 1.0.9

**Comment by Eufranio** [comment]
Working now! Thank you! :smiley:
