### ISSUE TITLE
Rate limit crashes the server

### ISSUE THREAD

**Issue by marvin-bitterlich** [shadowfacts/DiscordChat#57]
Brief explanation of issue:
A when enough people chat and trigger the discord rate limit it throws an exception and crashes the server:

```

net.shadowfacts.discordchat.repack.net.dv8tion.jda.exceptions.RateLimitedException: The message got Rate-Limited. You are able to send messages again in 764 ms
    at net.shadowfacts.discordchat.repack.net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:185)
    at net.shadowfacts.discordchat.repack.net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:161)
    at net.shadowfacts.discordchat.discord.DiscordThread.sendMessageToAllChannels(DiscordThread.java:75)
    at net.shadowfacts.discordchat.ForgeEventHandler.onPlayerLoggedOut(ForgeEventHandler.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_53_ForgeEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130)
    at org.spongepowered.mod.event.SpongeForgeEventFactory.callPlayerLoggedOutEvent(SpongeForgeEventFactory.java:1260)
    at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:425)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:332)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:384)
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:369)
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140)
    at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$0(NetHandlerPlayServer.java:526)
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:802)
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
```

Steps to reproduce:
- Step 1 chat a lot
- Step 2 watch is crash

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/Kostronor/dc431a520a610cbebe15de9953a1eda0
DiscordChat version:
DiscordChat-1.10.2-1.4.0.jar
Minecraft version:
1.10.2

**Comment by dannydjdk** [comment]
This is crashing our server sometimes several times a day on busy days. Not sure if this will give you more info than you already have, but in case it helps, here's a crash report: http://pastebin.com/BKKWwpLk

**Comment by marvin-bitterlich** [comment]
We found that a server shutdown with a /kickall will trigger the ratelimit and crash the server while it was shutting down, resulting in rollbacks all over.

**Comment by marvin-bitterlich** [comment]
@dannydjdk I suggest you use https://minecraft.curseforge.com/projects/discordintegration for now. It seems this bug won't be merged fast even if a fixing pr is open.

**Comment by shadowfacts** [comment]
The PR hasn't been merged because 1) the fix hasn't been tested and 2) I'm planning to rewrite the mod

**Comment by marvin-bitterlich** [comment]
Thanks for clearing that up @shadowfacts 
Until said rewrite happened, I suggest all viewers to go with https://minecraft.curseforge.com/projects/discordintegration (that is what I've done and it handles ratelimits gracefully)

**Comment by shadowfacts** [comment]
Rate limiting is now handled gracefully with a message queue in the rewrite.
