### ISSUE TITLE
Apache commons logging dependency not resolved in repack

### ISSUE THREAD

**Issue by ikkerens** [shadowfacts/DiscordChat#67]
Brief explanation of issue:
Since the latest version (2.0.1 and 2.0.2) that I tested I noticed that the plugin refuses to start properly. After some research I have found that apache commons logging is looking for `org.apache.commons.logging.LogFactory` whereas you have repacked it as `net.shadowfacts.discordchat.repack.org.apache.commons.logging.LogFactory`.
This causes several NullPointerExceptions later on.
From what I can see issues #64 and possibly #65, #66 as well.

Should you require any further information please let me know, as a java developer myself I may be able to give detailed information.

Steps to reproduce:

- Step 1
Install the mod to a server that does NOT have any other references to apache commons logging.
- Step 2
Start the server.

Link to crash report/log in a [gist](https://gist.github.com):
Relevant stacktrace:
```
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.commons.logging.LogFactory.class$(LogFactory.java:1021)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:1674)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:60)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:43)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:45)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.com.mashape.unirest.http.options.Options.refresh(Options.java:72)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.Requester.execute(Requester.java:114)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.Requester.request(Requester.java:75)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.requests.RestAction.block(RestAction.java:80)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:166)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:104)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:355)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:378)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.shadowfacts.discordchat.core.DiscordChat.lambda$connect$0(DiscordChat.java:87)
[21:01:44] [DiscordChat-initializer/INFO] [STDERR/discordchat]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.run(Unknown Source)
```

NullPointerException after failed start:
```
java.lang.NullPointerException
	at net.shadowfacts.discordchat.core.DiscordChat.sendMessage(DiscordChat.java:189) ~[DiscordChat.class:?]
	at net.shadowfacts.discordchat.one_seven_ten.OneSevenTenMod.serverStarted(OneSevenTenMod.java:46) ~[OneSevenTenMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Full log:
https://gist.github.com/Ikkerens/9f1c3e01ae1c3f9fda4ef04539f02574

DiscordChat version:
2.0.1 and 2.0.2 (and possibly more)
Minecraft version:
1.7.10

**Comment by shadowfacts** [comment]
34a785f2870e43ff5d255ea346405c4208e9bf5f fixes the NPE.
