### ISSUE TITLE
Bot stops conveying messages from server after some time

### ISSUE THREAD

**Issue by kzkv** [shadowfacts/DiscordChat#74]
Hey, 

We have 1.10.2 server with DiscordChat v2.0.3; after some hours bot stops posting messages from server to Discord channel, while it keeps sending messages from the channel to the server.

After restarting the server everything comes back to normal operations for a while.

I didn't catch the exact time the bot stops working, so I grabbed two might-be-relevant snippets I found in the logs, here it is: 

```
[19:39:33] [DiscordChat-send-queue/ERROR] [discordchat/discordchat]: Uncaught exception in DiscordChat-send-queue thread
net.shadowfacts.discordchat.repack.net.dv8tion.jda.core.exceptions.ErrorResponseException: Discord returned an unknown error type : {"code": 0, "message": "errors={'10.10.0.148': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.10.0.148"}
	at net.shadowfacts.discordchat.core.DiscordChat.lambda$start$1(DiscordChat.java:103) ~[DiscordChat.class:?]

[04:38:42] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[?:1.8.0_111]
	at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_111]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_111]
	at net.shadowfacts.discordchat.core.MessageFormatter.fromMC(MessageFormatter.java:22) ~[MessageFormatter.class:?]
	at net.shadowfacts.discordchat.one_ten_two.ForgeEventHandler.onServerChat(ForgeEventHandler.java:23) ~[ForgeEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_243_ForgeEventHandler_onServerChat_ServerChatEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:623) ~[ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:897) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[04:38:46] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[?:1.8.0_111]
	at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_111]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_111]
	at net.shadowfacts.discordchat.core.MessageFormatter.fromMC(MessageFormatter.java:22) ~[MessageFormatter.class:?]
	at net.shadowfacts.discordchat.one_ten_two.ForgeEventHandler.onServerChat(ForgeEventHandler.java:23) ~[ForgeEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_243_ForgeEventHandler_onServerChat_ServerChatEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:623) ~[ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:897) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

Next time I notice the bot stopped sending messages I'll try to grab the log output for that exact time. 

Thanks for the mod, it's amazing, it allows the server community to participate even while not actually playing! :0)

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4.
